name: build

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      PROJECT_FILE: ./src/Dmc.Siemens/Dmc.Siemens.csproj
      NUGET_PATH: .nuget

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.201
      - name: Install dependencies
        run: dotnet restore ${{ env.PROJECT_FILE }}
      - name: Build
        run: dotnet build -c Release --no-restore ${{ env.PROJECT_FILE }}
      - name: Pack
        run: dotnet pack -c Release --no-restore -o ${{ env.NUGET_PATH }} ${{ env.PROJECT_FILE }}
      - name: Push
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        run: dotnet nuget push ${{ env.NUGET_PATH }}/*.nupkg -k $NUGET_KEY -s https://api.nuget.org/v3/index.json
